[package]
name = "feroxide"
version = "1.2.0"
authors = ["C-Bouthoorn <cbouthoorn19@gmail.com>"]
build = "src/build.rs"

description = "A basic chemistry simulator"
documentation = "https://github.com/C-Bouthoorn/feroxide-gui"
homepage = "https://github.com/C-Bouthoorn/feroxide-gui"
repository = "https://github.com/C-Bouthoorn/feroxide-gui"

readme = "README.md"

keywords = ["chemistry", "simulator", "mit"]
categories = ["command-line-interface", "science"]

license-file = "LICENSE"

[badges]
travis-ci = { repository = "C-Bouthoorn/feroxide", branch = "master" }


[[bin]]
name = "main"
doc = false

[dependencies]
lazy_static = "0.2.4"


[build-dependencies]
toml = "0.3.1"
serde = "0.9.11"
serde_derive = "0.9.11"
