[package]
name = "feroxide"
version = "1.0.0"
authors = ["C-Bouthoorn <cbouthoorn19@gmail.com>"]
build = "src/build.rs"

[[bin]]
name = "main"
doc = false

[dependencies]
lazy_static = "*"


[build-dependencies]
toml = "0.3.1"
serde = "0.9.11"
serde_derive = "0.9.11"
