# Using data from https://en.wikipedia.org/wiki/Periodic_table_(large_cells)

[atoms.HYDROGEN]
number = 1
mass = 1.008
symbol = "H"
name = "hydrogen"
group = 1
diatomic = true

[atoms.HELIUM]
number = 2
mass = 4.002602
symbol = "He"
name = "helium"
group = 18
diatomic = false

[atoms.LITHIUM]
number = 3
mass = 6.94
symbol = "Li"
name = "lithium"
group = 1
diatomic = false

[atoms.BERYLLIUM]
number = 4
mass = 9.0121831
symbol = "Be"
name = "beryllium"
group = 2
diatomic = false

[atoms.BORON]
number = 5
mass = 10.81
symbol = "B"
name = "boron"
group = 13
diatomic = false

[atoms.CARBON]
number = 6
mass = 12.011
symbol = "C"
name = "carbon"
group = 14
diatomic = false

[atoms.NITROGEN]
number = 7
mass = 14.007
symbol = "N"
name = "nitrogen"
group = 15
diatomic = true

[atoms.OXYGEN]
number = 8
mass = 15.999
symbol = "O"
name = "oxygen"
group = 16
diatomic = true

[atoms.FLUORINE]
number = 9
mass = 18.998403163
symbol = "F"
name = "fluorine"
group = 17
diatomic = true

[atoms.NEON]
number = 10
mass = 20.1797
symbol = "Ne"
name = "neon"
group = 18
diatomic = false

[atoms.SODIUM]
number = 11
mass = 22.98976928
symbol = "Na"
name = "sodium"
group = 1
diatomic = false

[atoms.MAGNESIUM]
number = 12
mass = 24.305
symbol = "Mg"
name = "magnesium"
group = 2
diatomic = false

[atoms.ALUMINIUM]
number = 13
mass = 26.9815385
symbol = "Al"
name = "aluminium"
group = 13
diatomic = false

[atoms.SILICON]
number = 14
mass = 28.085
symbol = "Si"
name = "silicon"
group = 14
diatomic = false

[atoms.PHOSPHORUS]
number = 15
mass = 30.973761998
symbol = "P"
name = "phosphorus"
group = 15
diatomic = false

[atoms.SULFUR]
number = 16
mass = 32.06
symbol = "S"
name = "sulfur"
group = 16
diatomic = false

[atoms.CHLORINE]
number = 17
mass = 35.45
symbol = "Cl"
name = "chlorine"
group = 17
diatomic = true

[atoms.ARGON]
number = 18
mass = 39.948
symbol = "Ar"
name = "argon"
group = 18
diatomic = false


[atoms.IRON]
number = 26
mass = 55.845
symbol = "Fe"
name = "iron"
group = 8
diatomic = false

[atoms.BROMINE]
number = 35
mass = 79.904
symbol = "Br"
name = "bromine"
group = 17
diatomic = true

[atoms.IODINE]
number = 53
mass = 126.90447
symbol = "I"
name = "iodine"
group = 17
diatomic = true
